name: hydrana
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.13.1
  scoped_model: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
  - assets/images/can.jpeg
  - assets/images/champagne.jpeg
  - assets/images/coffee.jpeg
  - assets/images/liquor.jpeg
  - assets/images/pint.jpeg
  - assets/images/wine-bottle.jpeg
  - assets/images/bru-beer.jpg
  - assets/images/unsplash.jpg
  - assets/images/unsplashbeer.jpg

